@startuml

skinparam component {
    BackgroundColor white
    BorderColor #326ce5
    FontColor #326ce5
}

[Kubernetes Cluster] as k8s

package "Région 1" {
    [Node1] as n1
    [Node2] as n2
    k8s -down-> n1
    k8s -down-> n2
}

package "Région 2" {
    [Node3] as n3
    [Node4] as n4
    k8s -down-> n3
    k8s -down-> n4
}

@enduml