@startuml

skinparam package {
    BackgroundColor #fff
    BorderColor #bbb
    BorderThickness 2
    FontColor #326ce5
    TitleFontColor #326ce5
}
skinparam node {
    BackgroundColor #326ce5
    BorderColor white
    BorderThickness 4
    FontColor white
}

package "Kubernetes Cluster" {
  package "Région 1" {
      [Node1] as n1
      [Node2] as n2
  }

  package "Région 2" {
      [Node3] as n3
      [Node4] as n4
  }
}

@enduml
