@startmindmap
top to bottom direction

* Partition réseau - Cluster divisé (3 membres)
** Majorité indisponible (1 membre)
*** Leader dans majorité
****[#orange]:Perte du consensus, nouvelle élection impossible
etcd bloqué en lecture seule sans leader;
*****[#green]:Retour de la majorité (3 membres)
Retour du consensus
Résolution automatique;
*****[#red] Majorité HS : disaster recovery

*** Leader dans minorité
****[#orange]:Perte du consensus, pas de nouvelle élection
etcd bloqué en lecture seule avec leader;
*****[#green]:Retour de la majorité (3 membres)
Retour du consensus
Résolution automatique;
*****[#red] Majorité HS : disaster recovery

** Minorité indisponible (2 membres)
*** Leader dans majorité
****[#green] Consensus conservé, pas de nouvelle élection

*** Leader dans minorité
****[#green] Consensus conservé et nouvelle élection
*****[#green] Nouveau leader élu dans la majorité

@endmindmap
