@startmindmap
top to bottom direction

* 3 membres
**: Majorité indisponible
  (1 membre);
***: Leader dans majorité
  Leader failure;
****[#darkorange]: Perte du consensus
  nouvelle élection impossible
  etcd en lecture seule;
*****[#green]: Retour de la majorité
  (3 membres)
  Retour du consensus
  Résolution automatique
  la minorité se synchronise avec les données de la majorité;
*****[#red]: Majorité HS
  disaster recovery;

***:Leader dans minorité
  Follower failure;
****[#darkorange]: Perte du consensus
  pas de nouvelle élection
  etcd en lecture seule;
*****[#red]: Retour de la majorité
  (3 membres)
  Split brain - 2 leaders;
******[#darkorange] Il faut forcer une élection
*****[#red]: Majorité HS
  disaster recovery;

**:Minorité indisponible
  (2 membres);
***: Leader dans majorité
  Follower failure;
****[#green]: Consensus conservé
  pas de nouvelle élection;
*****[#green]: Retour de la minorité
  (3 membres)
  Résolution automatique
  la minorité se synchronise avec les données de la majorité;

***: Leader dans minorité
  Leader failure;
****[#green]: Consensus conservé
  et nouvelle élection;
*****[#green] Nouveau leader élu dans la majorité
******[#red]: Retour de la minorité
  (3 membres)
  Split brain - 2 leaders;
*******[#darkorange] Il faut forcer une élection

@endmindmap
