@startmindmap

top to bottom direction

* Partition réseau - Cluster divisé
** Majorité indisponible
*** Leader dans majorité
****[#orange] etcd en lecture seule
***** Retour de la majorité
******[#green] Résolution automatique
*****[#red] Majorité HS
******[#red] Disaster recovery
*** Leader dans minorité
**** Leader retiré
*****[#green] Nouveau leader élu dans la majorité
** Minorité indisponible
*** Leader dans majorité
****[#green] Leader reste leader
*** Leader dans minorité
**** Leader retiré
*****[#green] Nouveau leader élu dans la majorité

@endmindmap
