graph TB
    subgraph "zoneB"
        n3(Node3)
        n4(Node4)
        s1(Stockage VMWare)
    end
    subgraph "zoneA"
        n1(Node1)
        n2(Node2)
        s2(Stockage VMWare)
    end

    classDef plain fill:#fff,stroke:#ddd,stroke-width:4px,color:#fff;
    classDef k8s fill:#326ce5,stroke:#fff,stroke-width:4px,color:#fff;
    classDef cluster fill:#fff,stroke:#bbb,stroke-width:2px,color:#326ce5;
    classDef storage fill:#fff,stroke:#bbb,stroke-width:2px,color:#326ce5;
    class n1,n2,n3,n4 k8s;
    class s1,s2 storage;
    class zoneA,zoneB cluster;
    s1 <-.->|Pas de réplication| s2
