@startuml

skinparam cluster {
    BackgroundColor white
    BorderColor #bbb
    BorderThickness 2
    FontColor #326ce5
}

skinparam node {
    BackgroundColor #326ce5
    BorderColor white
    BorderThickness 4
    FontColor white
}

skinparam storage {
    BackgroundColor white
    BorderColor #bbb
    BorderThickness 2
    FontColor #326ce5
}

package "Région B" as zoneB {
    node "Control Plane 2" as cp2
}

package "Région A" as zoneA {
    node "Control Plane 1" as cp1
}

package "Voting Zone" as votingZone {
    node "CP / etcd 3" as etcd3
}

@enduml
