name: Build and deploy tag release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required dependencies
        run: ./setup.sh

      - name: Install and Build 🔧
        uses: addnab/docker-run-action@v3
        with:
          # renovate: datasource=docker depName=asciidoctor/docker-asciidoctor
          image: asciidoctor/docker-asciidoctor:1.87
          options: -v ${{ github.workspace }}:/documents
          run: |
            gem install asciidoctor-revealjs --pre
            sed -i 's,^:raftscope_url: .*,:raftscope_url: https://sylvainmetayer.github.io/talk-k8s-2-az/${{ github.ref_name }}/raftscope/,' index.adoc
            sed -i 's,^:base_url: .*,:base_url: https://sylvainmetayer.github.io/talk-k8s-2-az/${{ github.ref_name }},' index.adoc
            asciidoctor-revealjs -r asciidoctor-diagram /documents/index.adoc

      - name: Copy build to folder 📦
        run: |
          mkdir -p build/${{ github.ref_name }}/reveal.js/dist && \
          cp -r favicon.ico *.html images css js build/${{ github.ref_name }} && \
          cp -r reveal.js/dist/* build/${{ github.ref_name }}/reveal.js/dist/ && \
          cp -r reveal.js/plugin build/${{ github.ref_name }}/reveal.js/
          sed -i 's/var NUM_SERVERS = 5;/var NUM_SERVERS = 3;/' raftscope/raft.js
          cp -r raftscope build/${{ github.ref_name }}
          # https://github.com/JamesIves/github-pages-deploy-action?tab=readme-ov-file#required-setup
          # css is ignored, force delete
          find build/ -name .gitignore -delete

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: build
          branch: gh-pages
          clean: false
